default: &default
  adapter: mysql2
  host: 127.0.0.1
  encoding: utf8
  database: database
  username: user
  password: password

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default